

"use client";
import ThemeProvider from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* <body className="bg-white text-black dark:bg-gray-900 dark:text-white"> */}
      <body >
      <ThemeProvider>
          <Navbar /> 
          <main className="p-4">{children}</main> {/* Page content changes here */}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}



// "use client";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import { ThemeProvider } from "next-themes";

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
//         <Navbar /> 
// <main className="p-4">{children}</main> Page content changes here
//  <Footer/>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }



















































































// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
